version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: venkat2607/mysql:1.0
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: venkat2607/backend:1.0
    container_name: backend
    command: sh -c "sleep 30 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    #image: venkat2607/frontend:1.0
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend